export const pokeDex = [
    {
        pokemon: 'bulbasaur',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'venusaur-mega',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'ivysaur',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'charmander',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'charmeleon',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'charizard',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'charizard-mega-x',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'charizard-mega-y',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'squirtle',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'wartortle',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'blastoise',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'blastoise-mega',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'caterpie',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'metapod',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'beedrill',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'weedle',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'kakuna',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'beedrill-mega',
        captured: 0,
        encountered: 0
    }, {
        pokemon: 'pidgey',
        captured: 0,
        encountered: 0
    }
];